### ISSUE TITLE
Little Question

### ISSUE THREAD

**Issue by placebocurejava** [marcospereira/play-i18n-hocon#2]
Hi Marcos,

You told me in google groups this 👍 
Regarding to use a database to store the messages, you can implement your own version of play.api.i18n.MessagesApi and use it instead of the default one. Here is an example about how to do it:
https://github.com/marcospereira/play-i18n-hocon

I tried your sample...it has no link to database store translations messages!!!

**Comment by marcospereira** [comment]
Hey @placebocurejava,

> I tried your sample...it has no link to database store translations messages!!!

I've linked to this as a sample of how to replace the default implementation that depends on `messages.*` files. This is not a full implementation of what you want (store messages in a database).
